### ISSUE TITLE
zn_recvprepare没有定义

### ISSUE THREAD

**Issue by heber** [starwing/znet#1]
是否忘了提交了？

**Comment by starwing** [comment]
不是的，这个接口被废弃掉了。

如果要recv，可以直接zn_recv(tcp, zn_recvbuff(buff), zn_recvsize(buff), ...);
即可。

因为每次on_recv的时候都要调用的recvfinish本身就维护好了recvbuffer的状态，所以不再需要recvprepare了。直接触发接收即可。

同样的，发送的sendprepare是一个复制接口，这意味着你的数据肯定会被复制一遍，为了不这么做，你可以采用更底层的接口，这么使用：

```
zn_Buffer *b = zn_sendbuffer(buff);
/* do something with b */
if (zn_needsend(buff, b))
    zn_send(tcp, zn_sendbuff(buff), zn_sendsize(buff), ...);
```

通过buffer，你可以进行很多操作，你可以一个字符字符地添加内容（zn_addchar），你可以一次得到一块内存然后交由别人填充内容（zn_prepbuffsize+zn_addsize），你也可以直接拷贝数据（zn_addlstring）。接口和Lua的C API是一样的。

总而言之，*prepare接口本身已经不使用了。

文档啥的可能要等以后了，现在在做Lua绑定，做完以后就是select实现，之后才会开始做文档。

**Comment by ownwaterloo** [comment]
不关掉吗？

**Comment by starwing** [comment]
那关掉好了～
