### ISSUE TITLE
ZN_MAX_ADDRLEN

### ISSUE THREAD

**Issue by ownwaterloo** [starwing/znet#10]
不知道INET6_ADDRSTRLEN在windows下是个什么状况。
msvc/mingw(or cygwin?)的各个版本里自带的header里有没有？
因为windows下比较混乱的原因， 不直接用INET6_ADDRSTRLEN这个名字也行， 但目前用的值实在是太大了。。。 zn_PeerInfo和zn_Tcp非常大。。。

**Comment by starwing** [comment]
有没有啥规范啥的？能不能直接给一个最大的大小这样？

**Comment by ownwaterloo** [comment]
规范是说类似[这样](http://pubs.opengroup.org/onlinepubs/000095399/basedefs/netinet/in.h.html)的东西么？

> INET_ADDRSTRLEN
>     16. Length of the string form for IP. 
> INET6_ADDRSTRLEN
>     46. Length of the string form for IPv6.

**Comment by starwing** [comment]
嗯，那就50好了……

**Comment by ownwaterloo** [comment]
就46呀，怕什么。。。

**Comment by starwing** [comment]
46啊，也行 = =

**Comment by ownwaterloo** [comment]
closed via 64b994c7765174d88414bcdf95c029365f1bb4cb
