### ISSUE TITLE
GetQueuedCompletionStatusEx and event buffer size

### ISSUE THREAD

**Issue by ownwaterloo** [starwing/znet#11]
分摊系统调用开销。于是就和linux一样面临一个问题：用多大的buffer。。。？
太小的话，系统调用开销占的比例就高。比如znet_iocp.h里的[znS_poll](https://github.com/starwing/znet/blob/05f56101502ad3cd8fab6b9826e10787a6b203d0/znet_iocp.h#L653-L654)。
太大也不好，（在最坏被填充满的情况下）会过多占用缓存。比如znet_epoll.h里的[znS_poll](https://github.com/starwing/znet/blob/05f56101502ad3cd8fab6b9826e10787a6b203d0/znet_epoll.h#L711)。4096*12。。。 

so。。。 将buffer大小的选择权交给<del>，或者说责任推卸给，</del>用户？
具体做法么。。。 可以是：
- znS_poll(...,_EVENT_ buf[], size_t size); EVENT被分别定义为OVERLAPPED_ENTRY或epoll_event。
  用户想分配多大就分配多大，想怎么分配就怎么分配。
  或者更狠一点：
- znS_poll(...,void\* buf, size_t size); 内部用一个除法。。。 也许还需要提供一个alignment，给那些不打算用malloc或new的人。

**Comment by starwing** [comment]
是的，这个肯定需要做，不过需要有一段完整的时间。

我是这么想的，最理想的折衷肯定是zn_State里面包含一块内存干这个，select就是这么干的。交给用户的话，你说了align的问题，这玩意儿得自己算= =这挺麻烦的（不过其实还不是最麻烦的）。不过，如果用户给的buf过小怎么办？至少需要大于某个大小吧？这个需要检查吧？

我的倾向是，这个缓冲区意思意思一下，就直接给一个默认大小放struct里面得了= =

**Comment by ownwaterloo** [comment]
```
#ifdef __linux__
typedef struct epoll_data EVENT;
#else
...
#endif

extern size_t alignment_of_EVENT;
struct EVENT_pair
{
    EVENT fst;
    char snd;
};
size_t alignment_of_EVENT = offsetof(struct EVENT_pair,snd);
```

具体就看把哪些放在头文件中。。。
如果把EVENT放在头文件中， 用户自己想怎么分配就怎么分配。 反正定义都能看见。 只是要提醒别去摸里面的内容。
否则，可以把EVENT放在c文件里， 头文件里只暴露一个 extern size_t alignment_of_EVENT。给不用malloc或new的人使用。
不过这里只有头文件。。。

至于buffer过小。。。  要不就暴露个size。。。 或者暴露EVENT的定义。。。

就算要给默认大小。。。 也别放在那个struct里啊。。。  放里面的意义在哪里。。。  还不如现在这样用用栈上的。

**Comment by starwing** [comment]
额，不是说栈大小有限么……

我的想法是这样的，首先，我不希望用户用接口的时候很复杂，要准备这个那个的，其次，我不太喜欢在头文件里引入实现的细节。

所以，这两个方案都感觉有点那个啥……

**Comment by ownwaterloo** [comment]
准备这个准备那个的另一个说法就是配置这个配置那个。。。不是说好不包含策略吗。。。

再退而求其次。。。 

```
#ifndef ZN_MAX_EVENTS
#define ZN_MAX_EVENTS 4096
#endif
```

这不复杂了吧？ 一般不去理它， 想要调整时至少还有个法子可以调整。。。
当然。。。 总是有办法可以调整的。。。 直接改源代码。。。

另外。。。 目前全部的实现细节都在头文件里。。。

**Comment by ownwaterloo** [comment]
说要准备这个那个。。。 zn_connect才是比准备buffer复杂多了。。。
不管策略还是机制都不提供， 反正我这里是异步的， 你怎么用自己看着办。。。

如果最终是打算支持异步dns的， 又不想用户太麻烦。。。 还不如现在就先提供一个简单的实现让用户能用上。。。
最坏情况， 总是可以用线程。。。 另外也可以试试getaddrinfo_a或DnsQueryEx什么的。。。

**Comment by zsummer** [comment]
dns解析这种需求真的很有必要么~

**Comment by ownwaterloo** [comment]
那个。。。 不能解析dns的话。。。 使用会有一些限制吧。。。
比如。。。 需要使用外部服务的时候？ 发邮件？ 代理？
即使全使用LAN内部的。。。 也有一些时候会避免使用硬编码的ip。。。

**Comment by zsummer** [comment]
做开源和做项目一样 先给自己定位好 用20%的代码实现最核心的功能20%的代码打磨可以 满足95%的需求 剩下的5%的特殊场合下的特殊需求可能需要60%的代码来堆叠 对于开源项目来讲 这部分代码不必加 提供解决方案即可 谁用到谁去fork一份自己补 也不需要回馈 dns解析就是不必在znet里面支持的 真的有需求 在业务层解析是更好更可控的解决方案 话说回来  另外这种代码也影响程序实际运行的鲁棒性的

**Comment by ownwaterloo** [comment]
“与网络有关的程序，只有5%是需要dns解析的” 是这个意思？
假设我想做proxy。。。<del>不是开玩笑。。。 这事不太方便明说。。。</del> 总得有地方做这个事。。。
各种网络协议(http, ssh, smtp, ...)的client。。。 没dns怎么玩？
dns怎么会是5%特殊场合下的特殊需求了呢。。。 <- 认真脸。。。

另外， 如果只解决simple thing， hard problem留给用户去搞， 别人为什么要fork这一份然后自己去补？ 而不是fork另外一份甚至自己从头写得了。 
不解决麻烦是不会有人卖帐的， 和一大波连名字都不知道的库一个性质。

退一步说， 如果不打算在znet里弄 —— 不是暂时， 而是就不打算支持了。 预定想解决的问题只是一个统一的proactor接口， 甚至只是想有一个用起来顺手的东西， 那也行。。。
反正现在也没有说定位究竟是什么。。。
那样的话。。。 char const\* ip的接口不合适。。。  这个在 #12 里有提。。。

**Comment by zsummer** [comment]
请读完我的回复并认真想一想 我是很认真的

**Comment by ownwaterloo** [comment]
认真读哪部分啊？
是"znet不应该加dns"这个论点？ 还是"dns只是特殊场合才有的需求"，"有需要就自己fork"，"影响代码鲁棒性"这样的论据吗？
你又有认真看我的回复吗？

**Comment by starwing** [comment]
DnsQueryEx最小依赖好像是Win8………………要支持XP或者Win7估计只有线程了= =

**Comment by zsummer** [comment]
我逐一回答下.  
1. proxy是应用 并不一定需要dns解析,  http ssh smtp都是协议 和dns解析也没关系.  你列举的这些需求都不是硬性的必须有dns, 实际使用也是这, proxy ssh 基本上都是直接用ip而不是url网址.  
2. 不同的需求场合有行业内相对成熟的解决方案, 换句话说, 合适的语言用在合适的项目, C写的网络库来玩HTTP?   这不是20年前 , php干嘛的 nginx干嘛的?  
3. 你说到邮件, 用到网络库的地方, 属于邮件服务器的项目现在有几家 有几个项目?  这几个邮件项目用C写的?  20年前的老项目?  而且退一步说 其中有用C来写的核心节点(假定是大型分布式项目), 这些节点和dns解析有什么关系 内部节点会用dns解析?  
4. 我有说开源项目只解决simple thing而把hard problem留给用户? 别闹了.   我说的是核心功能和5%的边缘功能 并没有用esay和hard来分. 我强调这点就是让作者明白自己在做什么 要达成什么, 别在细枝末节纠结.  这里我在详细描述下.  能传播开来的开源项目分两种, 一种大而全 需要投入大量的人力和精力和持久的打磨的项目,  这种项目能流行开来的 本身作者或者公司就是很具有知名度和口碑的. 实现可以很复杂工程可以很庞大只要接口好用有文档说明就够了. znet这种并不是这样的. 所以我说另外一种, 足够简单(和简单不同), 可以文档缺少只有只言片语的描述 有几份demo代码就可以,  让大部分人很轻松的上手 至于上手后发现有少许自己特殊的需求 自己完全可以花几分钟就可以实现满足自己需求的代码(同一个小功能满足自己需求和能达到放进master版本里的代码质量是不同的).  
5. dns解析依赖dns服务器和本地配置, 这对于程序来说是一个不可控的风险. 用户的dns服务器故障,本地host文件被修改, 到达dns服务器的网络延迟, 还有gfw都会导致dns解析失败, 而直接使用ip就减少了这部分的不可控因素.  
6. 你以为我没认真看你的回复嘛~    如果觉得我的回答超出了本issue或者觉得我的回答没有道理 忽略就好了 .  我只是想表达 不需要追求大而全 每一行增加的代码都是有额外(这行代码本身的技术和需要花费的时间精力之外的)成本的.  只是玩玩而已除外.

**Comment by starwing** [comment]
嗯嗯，你们继续讨论一下~说的都挺对的，到时候我看看怎么实现就好~

ZN_MAX_EVENTS现在用户可以配置了，所以挪到了znet.h头文件里面，已经提交了~

**Comment by ownwaterloo** [comment]
@zsummer 

我对“znet是否应该支持dns”以及znet的定位一直持无所谓态度。
不过既然提到了，还是希望 @starwing 能给个定位。。。

吐槽的是“不应该支持dns”背后的论据而已，即：
1. dns是特殊需求。
2. 有特殊需求的人fork即可。

截至目前为止。。。 自认为吐槽依然有效。。。

我逐一回答下.

> 你以为我没认真看你的回复嘛~

这句话还给你。。。

> 如果觉得我的回答超出了本issue或者觉得我的回答没有道理 忽略就好了 .

issue list这么严肃的地方这么随便真的好吗。。。
如果觉得我的回答没有道理，还请花点时间教育教育。。。

> 我只是想表达 不需要追求大而全 每一行增加的代码都是有额外(这行代码本身的技术和需要花费的时间精力之外的)成本的. 只是玩玩而已除外.

我觉得这个作为“不支持dns”的论据就没什么可吐槽的。。。

> proxy并不一定需要dns解析

是我说得太含蓄，没说清楚是什么proxy吗。。。
就说两种常见的http proxy和socks5 proxy。

```
curl --proxy http://127.0.0.1:1212 twitter.com
# 将它理解为： 在各种浏览器里配置好http proxy并访问twitter
```

随后监听1212端口的程序就会收到一个http请求：

```
GET HTTP://twitter.com HTTP/1.1
Host: twitter.com
...
```

是不是必须解析dns？

```
curl --proxy socks5h://localhost:1212 twitter.com
# 将它理解为： 在各种浏览器里配置好socks5 proxy并让proxy作dns解析
```

随后监听1212端口的程序就会收到一个包含ATYP=DOMAINNAME的请求。
是不是依然必须解析dns？

```
curl --proxy socks5://localhost:1212 twitter.com
# 同样是socks5 proxy 将它理解为：
# 在各种浏览器里配置好socks5 proxy，浏览器自己负责解析twitter.com
```

退一步讲，即使DOMAINNAME address type在socks5中是可选的，不支持它的也能叫socks5 proxy。。。
但不支持dns解析的后果就是这个socks5 proxy访问不了一大票网站。
btw：twitter.com不是特指，印象中它是靠本地解析dns无法访问的网站之一。
如果twitter.com现在可以了，总有其他的大量的网站必须靠proxy解析dns才能访问。原因你懂的。。。

“proxy并不一定需要dns解析”，对。
但我指的那个proxy，如果不支持dns解析，那就没什么卵用。。。

> http ssh smtp都是协议 和dns解析也没关系

所以我前面才特别强调是它们的“客户端”。。。

假设curl_without_dns是一个和curl类似但只能这样使用的程序：

```
curl_without_dns http://???.???.???.???/foo/bar -H 'Host: foobar.com'
```

当你听说“X是一个http客户端”时，你心里的期望X是curl那样的程序而不是curl_without_dns那样的程序对吗？

甚至，如果按照这样的逻辑继续下去 —— 反正http只是协议(protocol)而已，其实和传输(transport)并没有关系是不是？
假设http_request是这样一个程序： 从命令行参数和stdin构造 http request并输出到stdout。

```
http_request host foobar.127.0.0.1.xip.io user-agent ... |
nc 127.0.0.1 80
```

也就是说它只负责http“协议”，不负责传输。
如果有人声称这样的程序是http客户端，那赵日天应该会表示不服。

我前面说“许多协议的客户端需要dns解析”，强调的是这样客户端能“用”，能“干活”，能“解决问题”。
只强调它们实现的协议本身，就好像进一家“饭店”，老板说“我们这只有米饭，因为是饭店嘛”。。。
而撇开dns就好像老板说“其实我们这里也提供菜，甚至是面食，但就是没筷子，它又不是食物嘛，自备或者手抓也能吃嘛”。。。

如果有“curl,openssh,mutt干嘛的”的疑问，见后面。。。

> 你列举的这些需求都不是硬性的必须有dns, 实际使用也是这, proxy ssh 基本上都是直接用ip而不是url网址.

为什么你的基本上都是我的特殊情况。。。

假设买了个vps用来做proxy。。。 这种情况下可以直接用ip，也可以依赖dns解析。
但是如果直接使用ip，当需要换另一个vps或者ip时，要改多少配置文件？

假设部署了一个， 比如 http://some_app.cloud.com/websocket_proxy 。。。
这种情况下，直接用some_app.cloud.com的ip也不是不可以。但是：
1. 同样需要处理ip变动。
2. vps的ip变动是自己主动产生的，不频繁的。而some_app.cloud.com的ip变动是完全不受控制的。
3. 无法享受到dns解析带来的“优化”，例如some_app.cloud.com根据地域或负载返回不同的ip。
4. 为了能正确送出Host:，依然需要将some_app.cloud.com填写在某处，假设这个某处真的存在的话。

再说ssh。

```
ssh 192.168.0.12
```

对比

```
ssh repo.foobar.com
ssh test.foobar.com
ssh db.foobar.com
ssh dbmaster.foobar.com
ssh dbstanby.foobar.com
```

目的应该够明显吧？除了“容易记忆”这在显然的好处之外，它也没有与下面这些因素耦合在一起：
1. 在哪里 —— LAN or WLAN?
2. 是不是同一个 —— 例如，也许多个name会映射到一个ip
3. 实际有多少个 —— 例如，也许一个name会映射到多个ip

对openssh来说确实有~/.ssh/config可以完成上面的部分需求，
但也存在其他ssh客户端以及背地里悄悄使用ssh协议的软件，它们不一定（或者说基本不会）理会~/.ssh/config。

dns才是标准的、被广泛理解与支持的、application无关的“引入名字->位置这一间接层”的方式。
用config来解决本该由dns解决的问题只是workaround而已。

“没有硬性的必须有dns的需求”即使成立，也只是一句正确的废话。

> dns解析依赖dns服务器和本地配置, 这对于程序来说是一个不可控的风险. 用户的dns服务器故障,本地host文件被修改, 到达dns服务器的网络延迟, 还有gfw都会导致dns解析失败, 而直接使用ip就减少了这部分的不可控因素.

这个作为“在一些场景下我们应该直接使用ip，避免解析dns”的论据，并没有问题。
反之，也有为了那层间接性刻意不直接使用ip的情况。
这样的论述是想说明什么？是dns解析是特殊场合的特殊需求？还是这样的guide line才是特殊场合的特殊需求？

> 而且退一步说 其中有用C来写的核心节点(假定是大型分布式项目), 这些节点和dns解析有什么关系 内部节点会用dns解析?

前面已经说了，增加间接层也会带来一些好处。哪怕全是在LAN里。
而第5点里面说的那些dns的坏处，在一个可控的LAN里也没什么大不了的。

与ssh和其他直接或间接使用ssh协议的程序不同，这里说的程序是自己编写的，受控制的。
排除硬编码ip的方案，假设会采用：

```
IP fixed_during_execution = GETIP("service0.local");
atomic<IP> changed_on_sighup = GETIP("service1.local");
signal(SIGHUP, trigger_reconfiguration);
atomic<IP> changed_periodically = GETIP("service2.local");
start_timer(30_sec, refresh_ip);
IP changed_frequently() { return GETIP("service3.local"); }
```

如果GETIP是from_configuration而非dns_lookup，那这又是另一种application specific XXXconfig。
在“每一个”程序里面增加这样的“一丁点”复杂性，相比在（也许是同一个）网络库里进行dns的复杂性，一定是划算的？

同时也不要忽略dns相比plain config的其他优势：
1. 集中管理
DNSconfig vs XXXconfig + YYYconfig + ZZZconfig ...
2. DNS层的load balance
例如"pgmaster.local"总是解析到一个（可能会更便的）ip， 而"pgslave.local"（根据load）解析到多个ip之一。

repeat： 用config来解决本该由dns解决的问题只是workaround而已。

“内部节点会用dns解析?” 有可能不会，也有可能会。it depends...

其实从看到“dns解析这种需求真的很有必要么~”的一开始，我就在怀疑这句话的背景是不是：C/C++只适合编写可控LAN内核心节点上的服务，所以不需要dns。
1. 可控LAN内的dns
没它也能活。这一段想说明这种情况下dns并不是无用。所以我前面会说：即使在LAN内也有可能避免硬编码ip。
2. C/C++是不是只适合写这种程序？ 见后。

> 不同的需求场合有行业内相对成熟的解决方案, 换句话说, 合适的语言用在合适的项目, C写的网络库来玩HTTP? 这不是20年前 , php干嘛的 nginx干嘛的?
> 你说到邮件, 用到网络库的地方, 属于邮件服务器的项目现在有几家 有几个项目? 这几个邮件项目用C写的? 20年前的老项目?

再加上前面提到的可能出现的疑问：“curl,openssh,mutt干嘛的”。
按照这个逻辑 —— “不同的需求场合有行业内相对成熟的解决方案” —— libuv干嘛的？那用znet干嘛？
凭什么只有http应该用业内相对成熟的解决方案而网络库就不该或没有？
并且这与你在第4点里的分类是矛盾的。用第1类，即行业内相对成熟的解决方案就行了，第2类的存在价值又在哪里？

I. 我为了便于说明才选用http,ssh,smtp这一些常见协议名称。
如果引起你的误解，认为这是“特指”，那我换成“没dns怎么实现foo,bar,baz协议客户端”？ ok？
比如就是一个产品内部用的home made protocol：
1. 没有业内成熟的解决方案对吗？
2. 适合用C/C++写对吗？
至少适合用C/C++写底层，然后为某其他语言提供绑定继续写业务逻辑对吗？
3. 客户端需要dns对吗？
考虑ip变动或增加的时候，如果客户端支持dns，已经发布的客户端不需要任何改动。

II. “用行业内‘_相对_’成熟的解决方案就行了”，本是就是一个相对概念。
以http和MTA为例： apache <- nginx 以及 sendmail <- qmail。
前者也曾经是业内相对成熟的解决方案，不还是出现了业内更成熟的用C实现的解决方案？

III. 非C或C++语言的问题
假设有业内相对成熟的C方案，但它（们）的接口与该语言的绑定接口不匹配。
要么忍受这种不匹配，要么从C开始写。

IV. for fun
V. Not Invented Here
VI. 行政因素
VII. ...

> 我有说开源项目只解决simple thing而把hard problem留给用户? 别闹了. 我说的是核心功能和5%的边缘功能 并没有用esay和hard来分.

你确实没这样说。我不该用simple和hard。所以后面换成了“麻烦事”。我指的是这一段：

> 剩下的5%的特殊场合下的特殊需求可能需要60%的代码来堆叠

simple/hard/麻烦事那一段话是想吐槽的是第2点，即“fork即可”。

目前znet能做什么？
- windows/linux proactor —— select不算在feature里面行吗
- accept/connect —— 即可作server和client（但没有dns）
- tcp/udp
- ipv4 only
- lua bind?

还有吗？

如果有人发现它缺点什么功能 —— 不特指dns并且也不认为dns就是特殊的只有5%可能性的需求 —— 并且“有能力”自己补，你给我一个fork它而不是fork别的或者自己从头写的理由？
除了“我们是好基友”之外。。。

我能想到的情况就是：
1. 自己实现该库1.5倍(60%)的代码
都写了这么多了，干嘛还要用这40%的库并承受它的学习成本以及可能的风险？于是自己从头写了。
2. 找个另外的库补充这部分
虽然不用自己写，但也不会是恰好就只有1.5倍的代码量。再加上：
2.1 它们真的能很好整合？
2.2 这个库会不会本身就有znet的一部分甚至全部功能？
于是直接fork另一个库了。

越是坚持“精炼”并且不和“细枝末节”纠结就意味着：
1. 库其实并没有做什么难以达成的事情 —— 越容易被替代
2. 用户缺少的功能越多 —— 越想替代

最终结果，znet成为了一大帮作者自己了解并用得顺手的库之一，仅此而已。
这本身并没什么问题，但“fork即可”什么的都是自己骗自己。。。

**Comment by ownwaterloo** [comment]
@starwing 和事佬。。。 滚粗好吗~

如果已经有定位了不妨花点时间写下来，比如写到readme里。。。
如果还没有。。。其实也没什么大不了的。。。

无论是：
1. 直接提供async dns的功能
2. 提供和某一个或某一些async dns库整合的方式
3. 彻底不支持dns

都行啊。。。 有时间还是留个文档提一下对这个问题是怎么决定的。
1. 彻底不打算管dns？
提一下是良心，即使不给理由，也可以节省一部分人的时间：不管dns是吧？那没必要深究这个库了。。。
2. 打算处理？
最终想通过dns协议解决？ 整合其他库解决？
目前有thread/getaddrinfo_a,DnsQueryEx等实现或者直接等dns协议解决方案？
目前有考虑或者没考虑其他dns库？

DnsQueryEx不被广泛支持就算了呗，反正只是过渡而已。。。

**Comment by zsummer** [comment]
你说的很长, 但除了最后几句都是在说dns对客户端的重要性,   这个本身正确的,  但并没有反驳到我前面的任何回答, 客户端有客户端的应用场景, 服务器有服务器的, znet还是比较适合服务器搞东西,  把znet用在客户端本身这个做法就是属于边缘需求. 你的proxy的dns解析就是那5%的需求 这个还需要一而再再而三的强调嘛,  这种东西根本不需要用什么网络库, 自己调socket写写比用znet libuv asio还简单.  
你后面的想法, 我只能说你想多了.  如果每个用的人都要写相同的一份代码上去 这个块缺失的代码就不是5%的需求,  也说明开源的作者和维护者连哪些是核心需求重要需求哪些是边缘需求都没搞清楚.

**Comment by starwing** [comment]
@ownwaterloo 没啊，主要是我现在也拿不定主意，我可以接受的做法是这样的：
1. 用少数代码（不超过50行）实现DNS解析，或者至少每backend 50行。但是，这样做会导致每实现一个后端都会有DNS实现的依赖，我觉得不好。
2. 和事佬解决方法呗，做一个类似znet_buffer.h的库，叫znet_resolve.h都可以，专门做DNS解析，然后扔给znet用，提供联动的接口，所以对znet来说就是需要一个可以传递IP的通用接口，string的确感觉是浪费了点儿，不过至少支持性还是可以的，我们可以先讨论一下现在遇到的容错性上的问题。
3. 利用其他的库实现，转换成IP string，然后扔给znet。

对于第一点，其实IOCP有机制可以post一个OVERLAPPED给GetQueuedCompletionStatus的，我这边已经有方案了，但是这就是一个平台的，其他平台的还没想好，难道为了这个每次wait之前都去检查么= =比如说epoll_wait和getaddrinfo_a的结合性？如果说会给每个平台带来额外的负担，那我觉得还是单独写比较好，虽然对Windows来说的确可以在IOCP的分内做这个。

对于第二点，我是觉得这挺好的，也可以尝试类似的中间件的支持，不过架构上还需要想想，如果支持了，那么其实就可以往znet的流程里面插入其他的处理过程了，我觉得这个是好事儿。

对于第三点，和第二点类似，可以考虑只提供内部的中间件的回调接口，这个接口可以做很多事情，比如Log啊调试啊DNS啊等等，至于具体实现就甩锅给用户好了，或者自己要用的时候写一份然后贡献出来。具体和第二点没有区别，但肯定实现不会上传到这个仓库，因为znet的本意是没有依赖。

我觉得这就是个feature-request的事儿吧？不存在说“就决定了项目的定位”这么严肃的事儿。要说项目定位的话，就是能够简单地实现proactor的网络处理呗，希望用户简单，这就是设计中在意的事情。一方面提供简单的C接口，另一方面也方便绑定到其他的语言。利用一套简单的接口，脏活累活在里面藏起来了，这就是写znet的目的。但是，我还是希望它足够纯洁，至少不会有外部依赖，这样也是符合方便使用这个主旨的。

如果就feature-request而言，这个需求可以接受啊，但是关键难道不是看如何实现么？有时候如何实现并不一定需要写代码，而只是有一个方案就可以，比如甚至可以什么都不改，让外界做DNS，或者提供一个什么都不做的框架，外界可以插进来实现，或者自己做实现，关键还是在于这个东西希望怎么实现，以什么方式实现。

**Comment by ownwaterloo** [comment]
@zsummer

> znet还是比较适合服务器搞东西

为什么？ @starwing 写在这个项目某个地方了？ 还是他私下告诉过你？

> 把znet用在客户端本身这个做法就是属于边缘需求. 你的proxy的dns解析就是那5%的需求

为什么？ 同上。

> 这个还需要一而再再而三的强调嘛

除了proxy，前面说的其他东西就选择性忽略了？

> 这种东西根本不需要用什么网络库, 自己调socket写写比用znet libuv asio还简单.

为什么？ 在用户机器上的那套东西，是既要接受连接又要发起连接。

上面这几个陈述，你说得如此轻松，就好像它们显而易见是对的一样。
但在我看来，没有哪一个是站得住脚的，全都是显而易见缺乏根据的。
说话能有理有据**不要想当然**吗？

> 你后面的想法, 我只能说你想多了. 如果每个用的人都要写相同的一份代码上去 这个块缺失的代码就不是5%的需求, 也说明开源的作者和维护者连哪些是核心需求重要需求哪些是边缘需求都没搞清楚.

我只想问一句：你所说的所有这些那些，是你**对zsummer(X)的想法**还是你**对znet的想法**？
你能**区分这两者**吗？

**Comment by ownwaterloo** [comment]
@zsummer 
更正我上面说的一点。
无论是用户机器上还是外部机器上的东西，都是需要既接受连接又发起连接。
外部机器上显然（我可以说显然吧）会选择linux。
而用户机器就不受控制了，但linux用户本身基数少，并且linux用户能自己解决这事的比例高，所以win和mac反而是重点。

自己调socket写写？ 呵呵哒。。。

**Comment by zsummer** [comment]
想当然的以为自己的项目需求就是开源网络库需要都实现的需求   呵呵.

**Comment by zsummer** [comment]
需要既接受连接又发起连接  难道这样就很复杂了?    自己写写就知道了.

**Comment by ownwaterloo** [comment]
@zsummer 

> 想当然的以为自己的项目需求就是开源网络库需要都实现的需求 呵呵.

我从一开始的态度就是znet加不加dns无所谓。
proxy只是反驳"dns属于特殊需求"的例子**之一**。
想当然认为所有项目都是和自己的项目一个样， 呵呵哒。。。

> 需要既接受连接又发起连接 难道这样就很复杂了? 自己写写就知道了.

并没有意图说明它有多简单或多复杂， 想反驳的是**根本不需要网络库**， 以及你说话有多么不过脑。

> 这种东西根本不需要用什么网络库, 自己调socket写写比用znet libuv asio还简单.

从“根本不需要什么网络库”， 变成了“难道这就很复杂了”？
来来来， 我看看你还能怎么继续show， 啧啧啧。

还说什么自己写写就知道了， 我只想说， 你能先想想再说话吗？

**Comment by zsummer** [comment]
前面我回答的足够了说明问题了.    你自己挑几个语言上的字眼反驳来反驳去, 自己倒是把自己说嗨了 但却没有反驳出任何有价值的理由, 完全是玩言语上的技巧而已.   自己多想想吧.  自己沉浸在自己的世界里 没人能说服你.  更不会有人花大量的时间和你在这里争论这种没意义的事情 .

**Comment by ownwaterloo** [comment]
@zsummer 

> 前面我回答的足够了说明问题了.

我也有同感唉。。。  只是你觉得已经足够说明的东西和我觉得的应该是不一样的。

> 你自己挑几个语言上的字眼反驳来反驳去, 自己倒是把自己说嗨了 但却没有反驳出任何有价值的理由, 完全是玩言语上的技巧而已. 自己多想想吧.

dns就是特殊需求 -> proxy根本不需要网络库 -> 直接socket写又不复杂
用一个口胡去掩盖另一个口胡， 真是醉了。 你逻辑这么混乱， 也怪我挑字眼咯？

“却没有反驳出任何有价值的理由”？ 你还真是<del>自以为是</del>自信满满呐。。。

> 自己沉浸在自己的世界里 没人能说服你. 更不会有人花大量的时间和你在这里争论这种没意义的事情 .

前半段依旧还给你。
后半段， 不服来战。 我倒要看看你下限在哪里。

**Comment by zsummer** [comment]
......     自己慢慢有'上限'的嗨吧

**Comment by ownwaterloo** [comment]
@zsummer show，继续show。
