### ISSUE TITLE
problematic inet_addr

### ISSUE THREAD

**Issue by ownwaterloo** [starwing/znet#12]
这个函数无法区分错误。。。 可以用getaddrinfo。。。  除了可以检查错误外，它可以同时处理v4(比如"127.0.0.1")和v6("::1")。 但用起来比较麻烦， 还不知道windows上是不是支持。。。
不管怎样也得把inet_addr给排除掉。。。

另外。。。 是不打算解析地址吧。。。  但const char *addr这样的参数。。。
zn_connect不解析地址，总有一个地方要解析， 一般就直接解析成二进制形式了， 然后再转成字符串传进来？？？

**Comment by starwing** [comment]
话是这么说= =不过，是期望在znet类型隔离的，那传啥好呢= =void*的buf么= =

**Comment by ownwaterloo** [comment]
支持ipv6吗。。。 我看目前是没这打算。。。 那么socket和WSASocket的参数是死的。。。 就connect需要addr）或者再加一个len）。
socket addr这块丑得一逼， 不知道当初那些人是怎么想的， 每次都要cast一下。。。 感觉并没有什么乱用。。。
不如直接用const void*免得让用户再cast了。

**Comment by starwing** [comment]
getaddrinfo有，不过最小系统依赖是Vista或者Win8.1

**Comment by starwing** [comment]
另外，貌似这个函数会阻塞啊= =

**Comment by ownwaterloo** [comment]
windows简直水深火热-_-

```
hints.ai_flags ｜= AI_NUMERICHOST；
getaddrinfo(node, service, &hints, &res);
```

> If  hints.ai_flags  contains the AI_NUMERICHOST flag then node must be a numerical network address. The AI_NUMERICHOST flag suppresses any potentially lengthy network host  address lookups.

为什么是vista（这是win6吧)和win8.1？ win7怎么跳过了。。。

inet_pton/inetPton,inet_aton呢？ 它们至少会检查(很可能来自用户的)输入。。。

**Comment by starwing** [comment]
InetPton 同样是8.1才有= =

**Comment by starwing** [comment]
我自己实现了一个pton和ntop，这个问题已经解决掉了
