### ISSUE TITLE
asynchronize getaddrinfo/getnameinfo

### ISSUE THREAD

**Issue by starwing** [starwing/znet#14]
@ownwaterloo 计划加入 getaddrinfo 和 getnameinfo 的功能了。主要的动机其实是异步执行耗时任务，也就是线程池，如果不想自己写mysql的协议，那么异步执行阻塞任务其实是很重要的事情。

那么，目前的工作就成了：
1. [X] 加入异步任务功能，zn_Work
2. [x] 利用异步任务，实现异步的getaddrinfo和getnameinfo功能
3. [ ] 添加异步任务的Lua绑定（可能会比较麻烦，毕竟Lua无法多线程执行，可能需要新建一个lua_State执行异步的任务）。

**Comment by starwing** [comment]
@ownwaterloo getaddrinfo已经实现了，话说getnameinfo是干嘛的= =

**Comment by ownwaterloo** [comment]
@starwing "223.202.33.211"(的binary形式， 手算不方便。。。) -> "chinaunix.net" 和 80 -> "http"。。。
会用到这个吗。。。

**Comment by ownwaterloo** [comment]
呃， 是在额外线程里面执行阻塞调用实现的是吧。。。
不调用InitializeCriticalSection没关系吗。。。

**Comment by ownwaterloo** [comment]
你是打算链接到msvcrt的吧？ 那最好用_beginthreaex(好像是叫这名)而不是CreateThread。。。

**Comment by starwing** [comment]
额？用_beginthreadex有啥好处不？貌似是说会初始化一些msvcrt的状态是吧？我是打算尽量在线程里面不用crt的~暂时打算是改用GetAddrInfoW和MultiByteToWideChar这样。

额= =真的忘掉了InitializeCriticalSection了= =我昨天就是测试过了Mac上的，还没来得及测Windows，Windows也就是编译过了而已，看来我还是得再买台Windows的笔记本= =

getnameinfo真的有必要么= =有么~

**Comment by starwing** [comment]
娘的，为了调用那个该死的InitializeCriticalSection，我不得不自己用Interlocked系列函数手写了一个自旋锁= =

**Comment by ownwaterloo** [comment]
getnameinfo我也觉得好像用不上哎。。。

**Comment by ownwaterloo** [comment]
如果CreateThread， 并且又调用了需要初始化的东西， 还是会被初始化， 但没机会释放了 —— 记得是这样。。。。
但是。。。 写crt的人就不能在线程退出的通知里释放掉么。。。 以前怎么没有过这样的疑问。。。

CreateThread还有一个避免不了的问题是。。。  如果线程里使用了signal相关的东西， 好像是会挂的。。。 这个没法延迟初始化。。。

**Comment by ownwaterloo** [comment]
如果没有“不链接msvcrt， 只链接到kernel32.dll等”的打算， 用_beginthreadex就没什么坏处对吧。。。

不用考虑各种乱七八糟的事情。。。
比如， 这个线程是只跑固定的任务， 整个调用链是可控制的？ 还是会让库的用户提交一些函数来跑？
用户会不会使用crt或者signal？ 写文档警告他们？ 他们不看又怎么办？
假设windows下确实没有人会用signal。。。
那么， 是不是就只创建固定个数的线程， 永久性的跑？ 即被提交的任务只是在线程函数的一个循环里面跑。 
这样其实不算泄漏吧？ 就像主线程里malloc然后开始跑一个无限循环， 要释放它反而很麻烦。。。
还是说， 线程池里面的线程数量会按需要增加减少？
用_beginthreadex就省心。。。

**Comment by starwing** [comment]
znet不存在这种问题，因为znet的所有线程都不打算使用crt（包括signal）。

不过loki可能要考虑一下了，因为loki的主要操作在线程里面，而且是调用用户提供的回调函数。当然，各个线程（理论上）是不打算退出了，会一直用到结束。所以资源泄露应该没事儿。而且loki应该不会在线程里面signal的。这方面也还好……不过，为了安全起见是不是得考虑下_beginthreadex = =我要去看看文档……

**Comment by starwing** [comment]
getaddrinfo就一个线程，还是静态的，这个不用考虑。

loki是多个线程，但是是lk_start指定线程数量，默认是CPU个数个。而且也不会动态增加。

**Comment by starwing** [comment]
理论上说，loki的各个线程应该不打算使用POSIX相关内容，而是仅仅是业务逻辑。对POSIX相关的内容，应该有其他的库来提供，而且应该不会使用Windows那残破的POSIX支持= =嗯，我会写很多调用Windows API来实现的模块的

不过我找到了这个：https://support.microsoft.com/en-us/kb/104641 ，说malloc(), fopen(), _open(), strtok(), ctime(), or localtime()会造成大概80byte的内存泄漏。嗯，那我还是改改loki和这里的zn_task.h好了，毕竟zn_deque.h并没有创建线程。

另外我会仔细检查zn_getaddrinfo.h，看看到底需不需要改

**Comment by ownwaterloo** [comment]
嗯？  目前是把会阻塞的放在线程里来配合其他的异步部分吧？ 这个机制就只打算自己悄悄用， 不暴露给用户的用的？

**Comment by starwing** [comment]
嗯，getaddrinfo是自己用。zn_task是给用户回调，这个肯定得改，然后是loki也得改。但是getaddrinfo也得先看看实现，有没有调用一些不该调用的函数，如果没有的话才不需要改~

**Comment by starwing** [comment]
= =妈蛋，worker调用了zn_post，zn_post可能会调用malloc()，得改= =

**Comment by ownwaterloo** [comment]
对哦。。。 肯定要链接msvcrt的嘛。。。  不然怎么malloc。。。   那么， 用_beginthreadex 就没有什么坏处对不对。。。？

**Comment by ownwaterloo** [comment]
那。。。   把malloc改掉。。。 换HeapAlloc那套。。。？  要玩火吗。。。

**Comment by starwing** [comment]
疯了= = HeapAlloc这个就有点过分了= =

嗯，我改好了= =

**Comment by starwing** [comment]
我都有点不太想维护Windows版本了= =毕竟现在Mac用着~但是但是，VS真TMD好用啊= =

VS做的这么好用，怎么各种库那么垃圾= =

**Comment by ownwaterloo** [comment]
看你有没有msvcrt-free的意图啊。。。  有的话就HeapAlloc/CreateThread。。。   不然用_beginthreadex没什么坏处吧。。。

**Comment by ownwaterloo** [comment]
嗯。。。 VS从以前就很好用。。。  不知道现在被改坏了没。。。

**Comment by starwing** [comment]
是没坏处，就是这函数名字不好看= =

msvcrt-free我倒是想啊 = =可是这也太难了，而且也就彻底没法portable了= =

**Comment by ownwaterloo** [comment]
原来是嫌弃它难看啊。。。

**Comment by starwing** [comment]
另外，znet彻底改写过了，现在是单头文件库了，直接include就能用。zn_lua是Lua绑定，支持buffer和addrinfo。剩下的几个zn_*.h头文件都是独立的单头文件库。写的这么用心，都没有几个star，桑心= =

**Comment by ownwaterloo** [comment]
讲道理。。。
没文档对不对？
所谓的单头文件库， 其实是为了应付Windows下没有package manager并不是一种良好的structure对不对？
还有一些话感觉是地图炮就不在这里说了。。。

**Comment by starwing** [comment]
这么简单的库到底需要个啥文档= =接口都不超过50个（是31个哦）

好吧，文档是吧，嗯，有时间写好了= =要不你帮忙写个？

哦，单头文件倒不是说Windows没package manager，主要说的是C没有package manager（其实Lua也没有一个很好用的，很直接很清晰的package manager，luarocks很有点水土不服），而且洁癖犯了~一个头文件多干净~

**Comment by ownwaterloo** [comment]
其实代码我都没怎么看懂。。。

apt-get install xxx-dev
brew install # mac 是这样？
然后include, -l 就完事了。。。  C语言依然没有package manager。。。

被惯坏后简直不知道windows里该怎么办了。。。

**Comment by starwing** [comment]
但这是系统级别的，意味着，这些库你不能放到代码仓库里面，你项目几十号人，每个人都得来一遍，看看node.js，人家直接一个install，仓库一个commit+push足够了，这样才能叫方便。所以最终如果是一个项目，那么single-header library仍然比apt和brew方便。

而且，apt什么的也会有自己的问题。比如如果有package manager，更新什么的就是一句话，但是apt？系统的，自己的，更别说你其实没什么控制权，比如brew install lua，居然给你装的是5.2，为什么不装5.3？因为他说5.3会和其他的软件不兼容——这是什么意思？意思是，这个manager实际上是给二进制用的，代码只是附带！这种情况下，你根本没法管代码层面上的更新。

所以，C的single header就是不得已的东西了。

**Comment by ownwaterloo** [comment]
在代码仓库里面放package.json和放devenv.sh(里面sudo apt-get ...)没区别吧？  区别就是不是跨平台的？

就是说。。。 单头文件是打算直接放在用它的项目的代码仓库里面使用的？
其实差不多的吧， 反正都是git add 一下。。。
这种用法本身 —— 将源代码放到项目仓库里 —— 怎么合并两者的改动啊。。。
怎么把上游的改动拉下来， 怎么把下游的改动推上去？

apt的问题。。。  权限其实对本地开发机其实没什么关系的吧。。。  要推开发环境， 我都是本地一个类似的机器， 之推编译后的产物。。。
没有一个独立的sandbox（类似python的virtualenv， npm不带-g）确实是个大问题。。。
项目自己有一份源代码拷贝来解决？ 那还是前面的问题， 怎么合并改动呢。。。

是给二进制用的啊。。。  一般来说都不会再编译一次， 比如现在单头文件里面的static function。

**Comment by starwing** [comment]
> 怎么把上游的改动拉下来， 怎么把下游的改动推上去？

可以考虑git submodule

> apt的问题。。。 权限其实对本地开发机其实没什么关系的吧。。。 要推开发环境， 我都是本地一个类似的机器， 之推编译后的产物。。。

多人合作怎么办，毕竟这里是公司

**Comment by ownwaterloo** [comment]
既然用submodule的话， 是不是单头文件无所谓的吧。。。

多人合作？ 多人共享使用局域网里某些个机器？
要真想解决权限问题 —— 即， 不要随便哪个人都上来乱搞 —— sudoers 。。。 只允许执行 sudo apt-get install 而不能 sudo 其他。。。 甚至只允许安装某一些package。。。
而你要5.2版本， 我要5.3版本这个真不好办。。。

**Comment by starwing** [comment]
submodule这个是要手动的，然而，package manager就可以自动了，比如nam install这种。

…………共享是不行的== 你得保证代码拉下来就能编译= = package.json这个可以install，但是仓库里面有一份可以编译的啊，setenv就不得不跑一下才行了，以这个网速，是不是down下来了还得打行命令去喝个咖啡？这肯定不行吧？

**Comment by ownwaterloo** [comment]
怎么又说回去了。。。  关于submodule你的意思到底是用还是不用？

用submodule， 方便库和项目之间相互合并改动。 可以清楚的查看有哪些commits在库的repo而不在项目的repo， 然后进行合并， 反之也是。
但用了submodule， single header library的意义又在哪里？
至于submodule要手动。。。 算是用submodule的一个新的问题？ 这是有多懒。。。

如果不用submodule， 即把库的源代码放在项目的repo里。
那库和项目之间又该怎么合并代码？
还是说项目从使用库一开始， 就是一个不太想和上游repo合并的fork？

**Comment by ownwaterloo** [comment]
setenv是指前面说的devenv？ 或者叫init-devenv？ 
package.json + npm install -g 和 init-devenv 有什么区别啊。。。 不都是要从网上下么。。。
木有 npm install (非global的) 确实是个问题。。。
还是说， 你指的是npm install 然后在add .node_modules, commit, push?

submodule是我问“把库的源代码直接放项目的repo里不好合并”时你提出的方案。 不是我把它拿来和package.json比的啊。。。

**Comment by starwing** [comment]
其实也没啥不好合并的啊，我指的就是local的repo啊，直接npm install + commit + push了啊，这种情况怎么就不好合并了？具体的说法是，自己做的模块，submodule，npm的模块，install+commit+push，这个在，比如说，node.js是很成熟了的啊，rust也是一样的。就是C/C++木有这种东西……

据说有个clib，不过我不是很敢用= =

**Comment by starwing** [comment]
一般情况下做了single-header就没打算给上游提供更新了吧？都是比如说，拷贝到上游，提交，这样。毕竟就只有一个文件嘛

**Comment by ownwaterloo** [comment]
本来想说， 可能是因为C/C++比较早。。。 但想了想不对， 去查了下。。。
C++出现到标准化之间， 依次出现了common lisp,haskell, python, lua, ansi common lisp, java, ruby, javascript 然后才是C++的标准化。。。
其实和C++同期的语言还挺多的。。。 它们都有包管理。。。 haskell, python, java的包管理都不止一代了。。。
要说复杂， haskell也是编译到native code的。。。
common lisp更是连"编译/构建"都没个准。。。 最传统的load/dump， 也有翻译到C然后编译的。。。
然而就C/C++没有这样的东西。。。

**Comment by ownwaterloo** [comment]
用submodule， 每次合并后， 两个仓库的历史是一致的。
用人肉"合并"， 历史就不一致了。。。  是内容一样的不同的仓库。 完全把版本控制架空了。
这是rebase+squash。。。

**Comment by starwing** [comment]
不是的，所谓人肉合并，是说把修改过的single-header拷贝到上游的仓库然后提交，然后下游（如果是submodule）直接合并（reset）或者（如果是人肉）直接提交。

因为是拷贝，所以single-header就方便了。
